services:
  db:
    image: postgres:15
    container_name: resiem-db
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5333:5432"
    volumes:
      - resiem-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: resiem-app
    depends_on:
      db:
        condition: service_healthy
    environment:
        TZ: Asia/Seoul
        PGTZ: Asia/Seoul
        SPRING_PROFILES_ACTIVE: docker
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5333/${POSTGRES_DB}
        SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
        SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
        SIEM_LOG_WATCH_DIR: /var/log/app
    ports:
     - "8081:8080"
    volumes:
        - ./logs:/var/log/app


volumes:
  resiem-db-data: